repos:
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.31.0
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0  # Use the ref you want to point at
  hooks:
  - id: trailing-whitespace
    stages:
    - commit-msg
  - id: end-of-file-fixer
    stages:
    - commit-msg
  - id: check-toml
    stages:
    - commit-msg
  - id: check-yaml
    stages:
    - commit-msg



- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.3
  hooks:
  - id: seed-isort-config
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-yaml
    exclude: ^test-data/.*$
    args:
    - --autofix
