repos:
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.31.0
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0  # Use the ref you want to point at
  hooks:
  - id: trailing-whitespace
    stages:
    - commit-msg
  - id: end-of-file-fixer
    stages:
    - commit-msg
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    stages:
    - commit-msg
- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    stages:
    - commit-msg
