repos:
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.31.0
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0  # Use the ref you want to point at
  hooks:
  - id: trailing-whitespace
    stages:
    - commit-msg
  - id: end-of-file-fixer
    stages:
    - commit-msg
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: # arguments to configure flake8
    # making isort line length compatible with black
    - "--max-line-length=88"
    - "--max-complexity=18"
    - "--select=B,C,E,F,W,T4,B9"

    # these are errors that will be ignored by flake8
    # check out their meaning here
    # https://flake8.pycqa.org/en/latest/user/error-codes.html
    - "--ignore=E203,E266,E501,W503,F403,F401,E402"
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.3
  hooks:
  - id: seed-isort-config
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort