[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "2.0.0"
tag_format = "$version"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
