[tool.commitizen]
name = "cz_conventional_commits"
version = "2.0.0"
tag_format = "$version"

[tool.isort]
profile = "black"
line_length = 88
known_third_party = ["numpy", "setuptools", "squarer"]

[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
(
  # The following are specific to Black, you probably don't want those.
   blib2to3
  | tests/data
  | profiling
  | \.git
  | .__pycache__
  | \.__pycache__
  | \.hg|
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)
'''
